spring:
  cloud:
    zookeeper:
      enabled: false # zookeeper 服务发现与注册默认关闭
eureka:
  client:
    enabled: false # eureka 服务发现与注册默认关闭

---
# Profile For Eureka
spring:
  profiles: eureka
eureka:
  client:
    enabled: true
    serviceUrl:
#      defaultZone: http://127.0.0.1:12345/eureka
      defaultZone: http://127.0.0.1:11111/eureka,http://127.0.0.1:22222/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
---
# Profile For Zookeeper
spring:
  profiles: zookeeper
  cloud:
    zookeeper:
      enabled: true
      connectString: 127.0.0.1:2181